---
- name: Upload parameters.yml
  template:
    src: "{{ playbook_dir }}/templates/parameters.yml"
    dest: "{{ ansistrano_release_path.stdout }}/app/config/parameters.yml"

- name: Create logs folder for symlinks
  file:
    path: "{{ release_logs_path }}"
    state: directory

- name: Install Composer dependencies
  composer:
    command: install
    arguments: --classmap-authoritative --no-scripts
    no_dev: yes
    optimize_autoloader: yes
    working_dir: "{{ ansistrano_release_path.stdout }}"
  
- name: Install Node dependencies
  npm:
    production: true
    path: "{{ ansistrano_release_path.stdout }}"

- name: Compile assets for production
  npm:
    name: run build -- --mode=production
    path: "{{ ansistrano_release_path.stdout }}"
  
- name: Setup directory permissions for var/logs
  become: true
  file:
    path: "{{ release_logs_path }}"
    state: directory
    mode: 0777
    recurse: true
