---
servers:
  - name: web01
    hostname: web01-vagrant
    box: bento/ubuntu-18.04
    box_version: "201912.14.0"
    ip: "192.168.10.21"
    memory: 1024
    cpus: 1
  - name: api01
    hostname: api01-vagrant
    box: bento/ubuntu-18.04
    box_version: "201912.14.0"
    ip: "192.168.10.31"
    memory: 1024
    cpus: 1
  - name: worker01
    hostname: worker01-vagrant
    box: bento/ubuntu-18.04
    box_version: "201912.14.0"
    ip: "192.168.10.41"
    memory: 1024
    cpus: 1

ansible_pubkey_path: ~/.ssh/id_rsa.pub
ansible_privkey_path: ~/.ssh/id_rsa
