---
- hosts: consumer
  
  become: yes
  serial: 1
  gather_facts: true
  debugger: on_failed

  vars_prompt:
    - name: git_branch
      prompt: 'Enter a branch to deploy'
      default: master
      private: no

  # allows composer install with --no-dev argument
  # environment:
  #   SYMFONY_ENV: prod 

  roles:
    - consumer