php_default_version_debian: "7.0"
php_enable_php_fpm: true
php_enable_webserver: false
php_webserver_daemon: "nginx"

php_display_errors: "On"
php_expose_php: "On"
php_memory_limit: "512M"
php_max_execution_time: "60"
php_max_input_time: "60"
php_max_input_vars: "1000"
php_realpath_cache_size: "32K"

php_file_uploads: "On"
php_max_file_uploads: "20"
php_post_max_size: "32M"
php_allow_url_fopen: "On"

php_date_timezone: "Europe/Paris"

php_packages:
  - php
  - php-dev
  - php-cli
  - php-fpm
  - php-common
  - php-gd
  - php-xml
  - php-zip
  - php-mbstring
  - php-pdo
  - php-apcu
  - php-opcache
  - php-json
  - php-curl
  - php-xdebug
  - php-sybase
  - php-oauth
  - php-mysql
  - php-pgsql
  - php-pear
