---
- name: APT | download cassandra C++ driver packages and dependencies
  get_url: 
    url: "{{ item }}"
    dest: "/tmp"
  with_items: "{{ cassandra_urls }}"

- name: APT | downgrade libssl-dev for debian/stretch hosts (required for cassandra-cpp-drivers)
  include_tasks: install-libssl.yml
  when:
    - ansible_facts['distribution'] is match("Debian")
    - ansible_facts['distribution_release'] is match("stretch")

- name: APT | install cassandra C++ driver
  apt:
    deb: "/tmp/{{ item }}"
  loop: "{{ cassandra_pkgs }}"
