---
- name: APT | download librdkafka
  get_url: 
    url: "https://github.com/edenhill/librdkafka/archive/v{{ librdkafka_version }}.tar.gz"
    dest: "/tmp/librdkafka.tar.gz"
    checksum: "{{ librdkafka_checksum }}"

- name: APT | extract .tar archive
  unarchive:
    src: /tmp/librdkafka.tar.gz
    dest: /tmp
    creates: /tmp/librdkafka-{{ librdkafka_version }}
    remote_src: yes

- name: APT | compile source code
  become: true
  shell: |
    ./configure --install-deps
    make
    make install
  args:
    chdir: /tmp/librdkafka-{{ librdkafka_version }}/
