---
- name: APT | download cassandra C++ driver dependencies
  get_url: 
    url: "{{ item }}"
    dest: "/tmp"
  with_items: "{{ libuv_urls }}"

- name: APT | download cassandra C++ driver packages
  get_url: 
    url: "{{ item }}"
    dest: "/tmp"
  with_items: "{{ cassandra_urls }}"

- name: APT | install cassandra C++ dependencies
  apt:
    deb: "/tmp/{{ item }}"
  with_items: "{{ libuv_pkgs }}"

- name: APT | install cassandra C++ driver
  apt:
    deb: "/tmp/{{ item }}"
  with_items: "{{ cassandra_pkgs }}"
