---
- hosts: 
  - web
  - api
  - worker
  - consumer

  become: true
  gather_facts: true
  debugger: on_failed

  roles:
    - geerlingguy.composer

  vars: 
    composer_path: /usr/local/bin/composer
    composer_keep_updated: true
    composer_version: '1.9.0'

    # The directory where global packages will be installed.
    composer_home_path: '~/.composer'
    composer_home_owner: root
    composer_home_group: root

    # A list of packages to install globally. See commented examples below for
    # usage; the 'release' is optional, and defaults to '@stable'.
    composer_global_packages: []
    # - { name: phpunit/phpunit, release: "4.7.x" }
    # - { name: phpunit/phpunit, release: "@stable" }

    composer_add_to_path: true
