---
- hosts: all

  become: true
  gather_facts: true
  debugger: on_failed

  vars:
    filebeat_version: '6.3.2'
    filebeat_checksum: 'sha512:154eb2b25fe1d64abf6934bfc3937d38fff27cb327e9a21a3746b4e3d988bbc94fb18a357d1a80c74211a1a754c660d5eb5fe13600616f199baf6cf9941541b8'
    filebeat_create_config: true
    filebeat_inputs:
      - input_type: syslog
        paths:
          - "/var/log/*.log"

    filebeat_output_elasticsearch_enabled: false
    filebeat_output_logstash_enabled: true
    filebeat_output_logstash_hosts:
      - "192.168.1.81:5044"

    filebeat_enable_logging: true 
    filebeat_log_level: warning
    filebeat_log_dir: /var/log/filebeat
    filebeat_log_filename: filebeat.log

  roles:
    - fidanf.filebeat
