---
- hosts: 
  - web

  become: true
  gather_facts: true
  debugger: on_failed

  roles:
    - geerlingguy.nodejs

  vars: 
    # Set the version of Node.js to install ("6.x", "8.x", "10.x", "11.x", etc.).
    # Version numbers from Nodesource: https://github.com/nodesource/distributions
    nodejs_version: "10.x"

    # The user for whom the npm packages will be installed.
    # nodejs_install_npm_user: username

    # The directory for global installations.
    npm_config_prefix: "/usr/local/lib/npm"

    # Set to true to suppress the UID/GID switching when running package scripts. If
    # set explicitly to false, then installing as a non-root user will fail.
    npm_config_unsafe_perm: "true"

    # Define a list of global packages to be installed with NPM.
    nodejs_npm_global_packages: 
      - node-sass
      - jslint
