- hosts: localhost
  become: yes
  # strategy: debug
  # debugger: on_failed

  vars_files:
    - vars/packages.yml
    - vars/php.yml
    - vars/php-pecl.yml

  tasks: 
    
    - name: "Install system dependencies"
      apt:
        package: "{{ system_pkgs }}"
        state: present

    - name: "Install PHP extensions"
      import_role:
        name: geerlingguy.php
      
    - name: "Update PECL"
      command: "pecl channel-update pecl.php.net"

    - name: "Download Cassandra C++ driver and dependencies"
      get_url: 
        url: "{{ item }}"
        dest: "/tmp"
      with_items: "{{ cassandra_urls }}"
    
    - name: "Install Cassandra C++ driver and dependencies"
      apt:
        deb: "/tmp/{{ item }}"
      loop: "{{ cassandra_pkgs }}"
      debugger: on_skipped

    - name: "Install PECL extensions"
      import_role: 
        name: geerlingguy.php-pecl

    - name: "Create PECL extensions .ini files"
      template: 
        src: extension.ini.j2
        dest: /etc/php/7.0/mods-available/{{ item }}.ini
        owner: root
        group: root
        mode: 0644
      with_items: "{{ php_pecl_extensions }}"

    - name: "Enable PECL extensions"
      shell: phpenmod {{ item }}
      with_items: "{{ php_pecl_extensions }}"
      
    - name: "Configure Xdebug extension"
      template: 
        src: xdebug.ini.j2
        dest: /etc/php/7.0/mods-available/xdebug.ini
        owner: root
        group: root
        mode: 0644

    - name: "Configure pdo_dblib (MSSQL) extension"
      template: 
        src: freetds.ini.j2
        dest: /etc/freetds/freetds.conf
        owner: root
        group: root
        mode: 0644

    - name: "Install and enable PECL propro, raphf, pecl_http extensions using script"
      script: "{{ playbook_dir }}/bash/php-http.sh"
