---
- name: supervisor | Ensure all programs are stopped
  shell: supervisorctl stop all
  register: supervisor_stop_output

# - debug: "var=supervisor_stop_output"

- name: supervisor | reread then remove kafkamanager program if present
  supervisorctl:
    name: kafkamanager
    state: absent
  