---  
- name: Copy .env.local file over the VM
  copy: 
    src: .env.local
    dest: "{{ ansistrano_release_path.stdout }}/.env.local"

- name: Create logs folder for symlinks
  file:
    path: "{{ release_logs_path }}"
    state: directory

- name: Refresh permissions for all files
  file:
    path: /opt
    owner: api
    group: ansible
    mode: 0775
    recurse: true

- name: Install Composer dependencies
  composer:
    command: install
    arguments: --classmap-authoritative
    no_dev: yes
    optimize_autoloader: yes
    working_dir: "{{ ansistrano_release_path.stdout }}"
  become_user: api

- name: Generate cached .env vars
  shell: composer dump-env prod
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
  become_user: api

- name: Copy Nginx vhost configuration file
  template: 
    src: api.conf.j2
    dest: /etc/nginx/sites-available/api.conf
    owner: root
    group: root
    mode: 0644

- name: Activate vhost with symlink
  file: 
    src: /etc/nginx/sites-available/api.conf
    dest: /etc/nginx/sites-enabled/api.conf
    state: link
  notify: 
    - restart nginx
    - restart php-fpm