---
- name: Ensure gluster configuration directory exists
  file:
    path: "{{ gluster_conf_dir }}"
    state: directory
  tags: ['storage']

- name: Ensure gluster mount point exists
  file:
    path: /mnt/gluster
    state: directory
  tags: ['storage']

- name: Copy scripts volume configuration file over the VM
  template:
    src: scripts.vol.j2
    dest: "{{ gluster_conf_dir }}/scripts.vol"
    owner: root
    group: root
    mode: 0644
  tags: ['storage']

- name: Mount scripts volume to fstab
  mount:
    src: "{{ gluster_conf_dir }}/gluster.conf"
    name: /mnt/gluster
    fstype: glusterfs
    state: mounted
  tags: ['storage']

- name: Copy SSL volume configuration file over the VM
  template:
    src: scripts.vol.j2
    dest: "{{ gluster_conf_dir }}/scripts.vol"
    owner: root
    group: root
    mode: 0644
  tags: ['storage']

- name: Mount SSL volume to fstab
  mount:
    src: "{{ gluster_conf_dir }}/ssl.vol"
    name: /mnt/gluster
    fstype: glusterfs
    state: mounted
  tags: ['storage']