---
- name: Ensure gluster configuration directory exists
  file:
    path: "{{ gluster_conf_dir }}"
    state: directory
  tags: ['storage']

- name: Ensure gluster mount point exists
  file:
    path: /mnt/gluster
    state: directory
  tags: ['storage']

- name: Copy configuration over the VM
  template:
    src: gluster.conf.j2
    dest: "{{ gluster_conf_dir }}/gluster.conf"
    owner: root
    group: root
    mode: 0644
  tags: ['storage']

- name: Add mount point to fstab
  mount:
    src: /etc/glusterfs/gluster.conf
    name: /mnt/gluster
    fstype: glusterfs
    state: mounted
  tags: ['storage']